# Generated by Django 5.1.3 on 2024-11-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.BooleanField(default=False),
        ),
    ]
